# Generated by Django 4.1.3 on 2023-02-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p256dh', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('endpoint', models.URLField()),
                ('user_agent', models.TextField()),
                ('keys', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.keys')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user_agent', 'endpoint'), name='unique_subscription_per_device'),
        ),
    ]
