# Generated by Django 5.2.17 on 2026-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_db_log_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_picture',
            field=models.ImageField(blank=True, help_text='Square WebP recommended; 640×640 is sufficient for retina displays.', null=True, upload_to='site/hero/'),
        ),
    ]
