# Generated by Django 5.2.17 on 2026-09-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_sitesettings_hero_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cv_headline',
            field=models.CharField(blank=True, help_text='E.g. "Head of Product | Engineer".', max_length=120, verbose_name='CV headline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cv_location',
            field=models.CharField(blank=True, max_length=80, verbose_name='CV location'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cv_picture',
            field=models.ImageField(blank=True, help_text='Optional; falls back to the hero picture.', null=True, upload_to='site/cv/', verbose_name='CV picture'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cv_summary',
            field=models.TextField(blank=True, help_text='Markdown; blank lines separate paragraphs.', verbose_name='CV summary'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
    ]
