# Generated by Django 5.2.17 on 2026-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_sitesettings_cv_headline_sitesettings_cv_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(help_text='Markdown supported. Keep the card concise.')),
                ('icon', models.CharField(choices=[('layers', 'Product practice'), ('globe', 'Regional autonomy'), ('users', 'People and coaching')], default='layers', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leadership_heading',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(help_text='Short hero introduction; Markdown supported.'),
        ),
    ]
