# Generated by Django 5.2.17 on 2026-10-02 09:30

from django.db import migrations


"""Initial editorial copy; runtime content is maintained in Django admin."""
HERO_COPY = (
    'I lead software product teams at Tesla in EMEA, combining technical depth '
    'with a focus on developing people and simplifying complex problems.'
)
LEADERSHIP_HEADING = 'Building products—and the teams that lead them.'
LEADERSHIP_CARDS = [
    ('Establishing a product practice', 'layers',
     'I helped build Tesla’s software product practice in EMEA, launching the SAF-T '
     'framework and Vehicle Registration Platform from zero. I then hired and '
     'developed product managers to take ownership and grow those products further.'),
    ('Earning regional autonomy', 'globe',
     'I helped EMEA Billing move from dependence on US development toward independent '
     'product decisions and delivery. Deep domain and technical knowledge built trust '
     'with our US counterparts, giving us a shared long-term strategy and the autonomy '
     'to execute within the global platform.'),
    ('Developing independent leaders', 'users',
     'The work I’m proudest of is helping people become confident product leaders. '
     'Through consistent coaching and working through difficult problems together, '
     'I’ve helped team members navigate stakeholder challenges, deepen their expertise, '
     'and take ownership of long-term product direction.'),
]


def seed_content(apps, schema_editor):
    settings = apps.get_model('shared', 'SiteSettings')
    cards = apps.get_model('shared', 'LeadershipCard')
    alias = schema_editor.connection.alias
    settings.objects.using(alias).update_or_create(pk=1, defaults={
        'about_text': HERO_COPY, 'leadership_heading': LEADERSHIP_HEADING,
    })
    for position, (title, icon, body) in enumerate(LEADERSHIP_CARDS):
        cards.objects.using(alias).create(title=title, body=body, icon=icon, position=position)


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_leadershipcard_sitesettings_leadership_heading_and_more'),
    ]

    operations = [migrations.RunPython(seed_content, migrations.RunPython.noop)]
