# Generated by Django 5.2.17 on 2026-10-02; retain records during the model rename.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('shared', '0008_seed_leadership_content')]

    operations = [
        # Fix the existing table name before renaming the Python model so old
        # and new API replicas can both read the cards during a rolling release.
        migrations.AlterModelTable(
            name='leadershipcard', table='shared_leadershipcard',
        ),
        migrations.RenameModel(old_name='LeadershipCard', new_name='HighlightCard'),
        migrations.AlterModelOptions(
            name='highlightcard',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'Highlight card'},
        ),
        migrations.AlterField(
            model_name='highlightcard', name='icon',
            field=models.CharField(choices=[('layers', 'Layers'), ('globe', 'Globe'), ('users', 'People')], default='layers', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings', name='show_skills',
            field=models.BooleanField(default=False, help_text='Show skills and languages on the website and printable CV.', verbose_name='Show Skills'),
        ),
    ]
