# Generated by Django 5.2.17 on 2026-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_highlight_cards_and_skills'),
    ]

    operations = [
        # Retain the existing column for old replicas during a rolling release.
        migrations.AlterField(
            model_name='sitesettings', name='leadership_heading',
            field=models.CharField(blank=True, db_column='leadership_heading', max_length=160, verbose_name='Highlights heading'),
        ),
        migrations.RenameField(
            model_name='sitesettings', old_name='leadership_heading', new_name='highlights_heading',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='highlights_eyebrow',
            field=models.CharField(blank=True, default='How I lead', help_text='Small text above the heading; leave blank to hide it.', max_length=80, verbose_name='Highlights eyebrow'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='highlights_nav_label',
            field=models.CharField(default='Leadership', help_text='Label used in the desktop and mobile navigation.', max_length=40, verbose_name='Highlights navigation label'),
        ),
    ]
