# Generated by Django 5.2.17 on 2026-10-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_alter_highlightcard_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='timeline_closing_body',
            field=models.TextField(blank=True, default='New problems, the same curiosity.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='timeline_closing_heading',
            field=models.CharField(blank=True, default='Still building.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='timeline_heading',
            field=models.CharField(default='Experience leading products and teams.', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='timeline_intro',
            field=models.TextField(blank=True, default='From engineering foundations to leading products and people.'),
        ),
    ]
