# Generated by Django 3.0.4 on 2020-03-29 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(editable=False)),
                ('created_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('location', models.CharField(max_length=50)),
                ('descript', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('visible', models.IntegerField(default=True)),
                ('attachment', models.ManyToManyField(to='portfolio.Attachment')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(editable=False)),
                ('created_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('content', models.TextField()),
                ('visible', models.IntegerField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
