# Generated by Django 3.0.4 on 2022-04-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('authorable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.Authorable')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('shared.authorable', models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('authorable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.Authorable')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('location', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pictures/', verbose_name='Header picture')),
                ('content', models.TextField()),
                ('attachments', models.ManyToManyField(blank=True, related_name='blog_post_related', related_query_name='blog_posts', to='shared.Attachment', verbose_name='attachment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('shared.authorable', models.Model),
        ),
    ]
