# Generated by Django 3.0.4 on 2020-03-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('authorable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.Authorable')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(editable=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Last modified date')),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('attachment', models.ManyToManyField(related_name='blog_post_related', related_query_name='blog_posts', to='resume.Attachment', verbose_name='Attachment')),
            ],
            options={
                'ordering': ['-created_date'],
            },
            bases=('resume.authorable', models.Model),
        ),
    ]
