# Generated by Django 3.0.4 on 2020-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200329_1700'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ManyToManyField(related_name='blog_post_related', related_query_name='blog_posts', to='resume.Attachment', verbose_name='%(Class)S Attachment'),
        ),
    ]
