# Generated by Django 4.0.2 on 2022-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_attachment_id_alter_authorable_created_by_and_more'),
        ('blog', '0002_auto_20220404_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='shared.Attachment', verbose_name='attachment'),
        ),
    ]
