# Generated by Django 3.0.4 on 2020-03-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200329_1936'),
        ('blog', '0002_auto_20200329_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=None, upload_to='pictures/', verbose_name='Header picture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ManyToManyField(blank=True, related_name='blog_post_related', related_query_name='blog_posts', to='resume.Attachment', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
