# Generated by Django 3.0.4 on 2020-04-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20200401_2152'),
        ('blog', '0003_auto_20200329_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('authorable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.Authorable')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Last modified date')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
            bases=('resume.authorable', models.Model),
        ),
    ]
