# Generated by Django 3.0.4 on 2021-01-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200409_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
