# Generated by Django 3.2 on 2022-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_project_content_type_alter_project_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(0, 'novice'), (1, 'basic'), (2, 'advanced'), (3, 'expert'), (4, 'professional')]),
        ),
    ]
