# Generated by Django 3.2 on 2022-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'idea'), (1, 'started'), (2, 'ongoing'), (3, 'completed')], default=3),
        ),
    ]
