# Generated by Django 4.1.7 on 2023-02-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumb/'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumb/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
