# Generated by Django 5.2.17 on 2026-09-25 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_entity_thumbnail_project_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('proficiency', models.PositiveSmallIntegerField(help_text='100 = native.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Proficiency (%)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='cv_proficiency',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set to show this skill as a bar on the printable CV.', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='CV proficiency (%)'),
        ),
    ]
