# Generated by Django 5.2.17 on 2026-09-25 06:36

from django.db import migrations, models


def keep_cv_selection(apps, schema_editor):
    Skill = apps.get_model('resume', 'Skill')
    Skill.objects.filter(cv_proficiency__isnull=False).update(show_on_cv=True)


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_language_skill_cv_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='show_on_cv',
            field=models.BooleanField(default=False, help_text='Show as a bar on the printable CV; the bar length follows Level.', verbose_name='Show on CV'),
        ),
        migrations.RunPython(keep_cv_selection, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='skill',
            name='cv_proficiency',
        ),
    ]
