# Generated by Django 5.2.17 on 2026-10-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_skill_category_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='narrative_body',
            field=models.TextField(blank=True, help_text='Short plain-text chapter introduction.'),
        ),
        migrations.AddField(
            model_name='education',
            name='narrative_heading',
            field=models.CharField(blank=True, help_text='Optional chapter heading before this entry.', max_length=160),
        ),
        migrations.AddField(
            model_name='education',
            name='timeline_summary',
            field=models.TextField(blank=True, help_text='Markdown preview; leave blank to use Description.'),
        ),
        migrations.AddField(
            model_name='education',
            name='transition_motif',
            field=models.CharField(choices=[('none', 'Automatic flowing path'), ('detour', 'Around a difficulty'), ('breakthrough', 'Through a roadblock')], default='none', help_text='Decorative transition before this entry. Geometry adapts to the screen.', max_length=16),
        ),
        migrations.AddField(
            model_name='experience',
            name='narrative_body',
            field=models.TextField(blank=True, help_text='Short plain-text chapter introduction.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='narrative_heading',
            field=models.CharField(blank=True, help_text='Optional chapter heading before this entry.', max_length=160),
        ),
        migrations.AddField(
            model_name='experience',
            name='timeline_summary',
            field=models.TextField(blank=True, help_text='Markdown preview; leave blank to use Description.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='transition_motif',
            field=models.CharField(choices=[('none', 'Automatic flowing path'), ('detour', 'Around a difficulty'), ('breakthrough', 'Through a roadblock')], default='none', help_text='Decorative transition before this entry. Geometry adapts to the screen.', max_length=16),
        ),
    ]
