apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" .}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" .}}
  template:
    metadata:
      labels:
        app: {{ include "postgres.fullname" .}}
        tier: backend
    spec:
      containers:
        - name: {{ include "postgres.fullname" .}}
          image: 'postgres:14.2'
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: portfolio
                  key: DATABASE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio
                  key: DATABASE_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: {{ include "postgres.fullname" .}}
