# Generated by Django 2.2 on 2019-05-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('descript', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Company')),
            ],
            options={
                'ordering': ['start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('level', models.CharField(choices=[(1, 'basic'), (2, 'advanced'), (3, 'expert'), (4, 'professional')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descript', models.TextField()),
                ('attachment', models.FileField(upload_to='projects/')),
                ('during', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Education')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('descript', models.TextField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('key_achievements', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Company')),
            ],
            options={
                'ordering': ['start_date'],
                'abstract': False,
            },
        ),
    ]
