# Generated by Django 2.2 on 2019-05-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20190506_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='resume/logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(upload_to='resume/projects/'),
        ),
    ]
