# Generated by Django 2.2 on 2019-05-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20190506_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
