# Generated by Django 2.2 on 2019-05-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20190506_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descript', models.TextField()),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('during', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Experience')),
            ],
        ),
    ]
