# Generated by Django 2.2 on 2019-05-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20190512_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descript', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='descript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='descript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='descript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='key_achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='descript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainpage.SkillCategory'),
            preserve_default=False,
        ),
    ]
