# Generated by Django 2.2 on 2019-05-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_auto_20190512_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
