# Generated by Django 2.2 on 2019-05-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20190512_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='during',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mainpage.Experience'),
        ),
        migrations.AlterField(
            model_name='project',
            name='during',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='mainpage.Education'),
        ),
    ]
