repositories:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
    - name: ingress-nginx
      url: https://kubernetes.github.io/ingress-nginx

releases:
    - name: portfolio
      namespace: portfolio
      chart: ./charts/portfolio
      values:
        - ./values/portfolio.yaml
    - name: postgres
      namespace: portfolio
      chart: ./charts/postgres
      values:
        - ./values/postgres.yaml
    - name: ingress-controller
      namespace: portfolio
      chart: ingress-nginx/ingress-nginx
      values:
        - ./values/ingress-controller.yaml
    - name: frontend
      namespace: portfolio
      chart: bitnami/nginx
      values:
        - ./values/frontend.yaml