# Generated by Django 3.0.4 on 2020-03-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('current', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=50)),
                ('descript', models.TextField(blank=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(blank=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'SkillCategories',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('url', models.URLField()),
                ('level', models.IntegerField(choices=[(1, 'basic'), (2, 'advanced'), (3, 'expert'), (4, 'professional')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.SkillCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(blank=True)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('during', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume.Education')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('current', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=50)),
                ('descript', models.TextField(blank=True)),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('key_achievements', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(blank=True)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('during', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='resume.Experience')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
