# Generated by Django 3.0.4 on 2020-03-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='company',
        ),
        migrations.AddField(
            model_name='education',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education_related', related_query_name='educations', to='resume.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='project',
            field=models.ManyToManyField(related_name='education_related', related_query_name='educations', to='resume.Project'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience_related', related_query_name='experiences', to='resume.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='project',
            field=models.ManyToManyField(related_name='experience_related', related_query_name='experiences', to='resume.Project'),
        ),
    ]
