# Generated by Django 3.0.4 on 2020-03-29 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0003_auto_20200329_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='authorable',
            name='modified_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='resume_authorable_related_modifier', related_query_name='resume_authorable_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='attachment',
            field=models.ManyToManyField(blank=True, related_name='resume_education_related', related_query_name='resume_educations', to='resume.Attachment', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='education_related', related_query_name='educations', to='resume.Project'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='attachment',
            field=models.ManyToManyField(blank=True, related_name='resume_experience_related', related_query_name='resume_experiences', to='resume.Attachment', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='experience_related', related_query_name='experiences', to='resume.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.ManyToManyField(blank=True, related_name='resume_project_related', related_query_name='resume_projects', to='resume.Attachment', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(upload_to='pictures/', verbose_name='Header picture'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
