# Generated by Django 4.0.2 on 2022-04-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resume', '0003_alter_education_attachments_alter_education_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
