# Generated by Django 3.0.4 on 2020-03-22 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200321_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='education',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='education',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='modified_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 12, 3, 12, 765832), editable=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
