# Generated by Django 3.0.4 on 2020-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200329_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='education_related', related_query_name='educations', to='resume.Project'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='experience_related', related_query_name='experiences', to='resume.Project'),
        ),
    ]
