# Generated by Django 3.0.4 on 2020-03-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '__first__'),
        ('resume', '0007_auto_20200328_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='attachment',
        ),
        migrations.AddField(
            model_name='education',
            name='attachment',
            field=models.ManyToManyField(to='portfolio.Attachment'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='attachment',
        ),
        migrations.AddField(
            model_name='experience',
            name='attachment',
            field=models.ManyToManyField(to='portfolio.Attachment'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='attachment',
        ),
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.ManyToManyField(to='portfolio.Attachment'),
        ),
    ]
