# Generated by Django 3.0.4 on 2020-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_project_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
