# Generated by Django 3.0.4 on 2020-04-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20200401_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
    ]
