# Generated by Django 3.0.4 on 2020-03-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '__first__'),
        ('resume', '0008_auto_20200329_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='project',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='descript',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='attachment',
            field=models.ManyToManyField(related_name='resume_education_related', related_query_name='resume_educations', to='portfolio.Attachment', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Is current'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='attachment',
            field=models.ManyToManyField(related_name='resume_experience_related', related_query_name='resume_experiences', to='portfolio.Attachment', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Is current'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.ManyToManyField(related_name='resume_project_related', related_query_name='resume_projects', to='portfolio.Attachment', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Last modified date'),
        ),
    ]
