# Generated by Django 3.0.4 on 2020-04-09 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200405_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
    ]
