# Generated by Django 3.0.4 on 2020-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20200409_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experiences'},
        ),
    ]
