# Generated by Django 3.0.4 on 2022-03-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resume', '0012_auto_20210111_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('name', models.SlugField()),
                ('object_id', models.UUIDField(primary_key=True, serialize=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
