# Generated by Django 3.0.4 on 2022-03-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20220322_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='current',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='education_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resume.Education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
