apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portfolio.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  DJANGO_LOGLEVEL: INFO
  EMAIL_TO: {{ .Values.configMap.emailTo | quote }}
  DEBUG: {{ .Values.configMap.debug | quote }}
  DATABASE_NAME: {{ .Values.database.name }}
  DATABASE_HOST: {{ .Values.database.host }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DB_ENGINE: {{ .Values.database.engine }}
  DJANGO_HOST: {{ .Values.configMap.djangoHost }}
