apiVersion: v1
kind: Service
metadata:
  name: {{ template "portfolio.fullname" . }}
  labels:
    app: portfolio
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: {{ template "portfolio.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
