# Generated by Django 5.2.17 on 2026-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactsubmission_delivery_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmissionLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='payload_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='source_key',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['source_key', 'submitted_at'], name='contact_source_time'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['payload_key', 'submitted_at'], name='contact_payload_time'),
        ),
    ]
