# Generated by Django 5.2.17 on 2026-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactadmissionlock_contactsubmission_payload_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
